apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE user-db;
    CREATE DATABASE routine_db;
    CREATE DATABASE letter_db;
    CREATE DATABASE letter_storage_db;
