apiVersion: apps/v1
kind: Deployment
metadata:
  name: letter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letter-service
  template:
    metadata:
      labels:
        app: letter-service
    spec:
      containers:
        - name: letter-service
          image: hyomee2/letter-service:latest # Docker Hub에 올린 이미지 이름
          imagePullPolicy: Always
          ports:
            - containerPort: 8006
          envFrom:
            - configMapRef:
                name: letter-config
            - secretRef:
                name: letter-secret
          volumeMounts:
            - name: letter-storage
              mountPath: /app 
          livenessProbe:
            httpGet:
              path: /health/
              port: 8006
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: 8006
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
      volumes:
        - name: letter-storage
          emptyDir: {}  # 필요 시 PVC로 교체 가능
