apiVersion: v1
kind: Service
metadata:
  name: letter-service
spec:
  selector:
    app: letter-service
  ports:
    - port: 8006  # 외부에서 접근할 포트
      targetPort: 8000  # 컨테이너 내부 포트
  type: ClusterIP
