# scheduler-beat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-beat
  template:
    metadata:
      labels:
        app: scheduler-beat
    spec:
      containers:
        - name: scheduler-beat
          image: nye0817/al2m-scheduler-service:v2
          command: ["celery", "-A", "scheduler_service", "beat", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: scheduler-config
            - secretRef:
                name: scheduler-secret