apiVersion: v1
kind: ConfigMap
metadata:
  name: letter-storage-config
data:
  DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,letter-storage-service"
  DB_ENGINE: django.db.backends.postgresql
  LETTER_STORAGE_DB_NAME: letter_storage_db
  LETTER_STORAGE_DB_USER: postgres
  LETTER_STORAGE_DB_HOST: postgres-service
  LETTER_STORAGE_DB_PORT: "5432"
  LETTER_STORAGE_SERVICE_BASE_URL: "http://letters-storage-service:8007"
