# Django 앱을 배포할 k8s deployment manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: letter-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letter-storage-service
  template:
    metadata:
      labels:
        app: letter-storage-service
    spec:
      containers:
        - name: letter-storage-service
          image: hyomee2/letter-storage-service:20250607-064403
          ports:
          - containerPort: 8007
          envFrom:
            - configMapRef:
                name: letter-storage-config
            - secretRef:
                name: letter-storage-secret
          livenessProbe:
            httpGet:
              path: /health/
              port: 8007
              # host: "127.0.0.1"
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: 8007
              # host: "127.0.0.1"
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always