apiVersion: v1
kind: Service
metadata:
  name: letter-storage-service
spec:
  selector:
    app: letter-storage-service
  ports:
    - port: 8007  # 외부에서 접근할 포트
      targetPort: 8007  # 컨테이너 내부 포트
  type: ClusterIP