# notification-service
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 8005
      targetPort: 8005
  type: ClusterIP

