# routine-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routine-service
  template:
    metadata:
      labels:
        app: routine-service
    spec:
      containers:
        - name: routine-service
          image: nye0817/al2m:routine-service
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: routine-config
            - secretRef:
                name: routine-secret
---
apiVersion: v1
kind: Service
metadata:
  name: routine-service
spec:
  selector:
    app: routine-service
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP