apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  labels:
    app: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web-client
        image: yeoncheong08/al2m-web-client # Docker Hub에 올린 이미지 이름
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        imagePullPolicy: Always
