apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: nye0817/al2m:user-service
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: user-secret
          livenessProbe:
            httpGet:
              path: /health/
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
